project:
  type: book

book:
  title: "Livre quarto"
  author: "Emmanuel Roch"
  date: "4/24/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



